### ISSUE TITLE
Time slots reset after choosing a time slot and clicking the Videoyu Kes

### ISSUE THREAD

**Issue by tuzumkuru** [alpaylan/babalaclips#3]
Upon selecting a specific time slot and clicking the "Videoyu Kes" button, it is reasonable to anticipate that the pre-determined time would be reflected as the chosen selection within the "Kaydet" window. However, instead of observing the expected time as selected, one is presented with the initial entry in the list, as if no selection had been made at all.

**Comment by alpaylan** [comment]
"Videoyu kes" button will reflect the current timestamp on the video. This is WIP right now, should be fixed within 2 hours.

**Comment by alpaylan** [comment]
Search is redesigned.

**Comment by alpaylan** [comment]
"Videodaki Ana Gel" button is added to the new cut UI.
